name: CI CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # code checkout 및 JDK 설정
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle 설정
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      # zip 파일 생성

      # AWS 자격 증명 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 배포 전 작업
      - name: Prepare files for deployment
        run: |
          echo "Zipping files..."
          zip -r posts-webservice *
          mkdir -p deploy
          mv posts-webservice.zip deploy/posts-webservice.zip
          echo "Files prepared in 'deploy/posts-webservice.zip'"

      # AWS S3로 업로드
      - name: Upload to S3
        run: |
          echo "Uploading to S3..."
          aws s3 cp deploy/posts-webservice.zip s3://freelec-springboot-build-zip/posts-webservice.zip \
            --region ap-northeast-2 \
            --acl private
          echo "Upload to S3 completed."
